name: Build avec Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Tu peux mettre '21' ou '11' selon la version de ton projet
        distribution: 'temurin'

    - name: Donner les droits d'exécution au wrapper Gradle
      run: chmod +x gradlew

    - name: Lancer le build Gradle
      run: ./gradlew build
